framework:
  secret: '%env(APP_SECRET)'
  http_method_override: true
  handle_all_throwables: true
  php_errors:
    log: true
  error_controller: olml89\TelegramUserbot\Backend\Shared\Infrastructure\Symfony\Http\Web\Controller\ErrorController::__invoke

  session:
    enabled: true
    cookie_secure: auto
    cookie_samesite: lax
