framework:
  secret: '%env(APP_SECRET)'
  http_method_override: true
  handle_all_throwables: true
  php_errors:
    log: true

  session:
    enabled: true
    cookie_secure: auto
    cookie_samesite: lax
