services:

  # EventEntityRepository
  olml89\TelegramUserbot\Backend\Shared\Domain\Entity\EventEntityRepository:
    alias: olml89\TelegramUserbot\Backend\Shared\Infrastructure\Doctrine\DoctrineEventEntityRepository

doctrine:
  # Types
  dbal:
    types:
      name: olml89\TelegramUserbot\Backend\Shared\Infrastructure\Doctrine\Types\NameType
      percentage: olml89\TelegramUserbot\Backend\Shared\Infrastructure\Doctrine\Types\PercentageType
  # Mappings
  orm:
    entity_managers:
      default:
        mappings:
          Shared:
            type: xml
            dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mappings'
            prefix: olml89\TelegramUserbot\Backend\Shared\Domain\Entity\EventEntity
            is_bundle: false
