services:

  # EventEntityRepository
  olml89\TelegramUserbot\Backend\Shared\Domain\Entity\EventEntityRepository:
    alias: olml89\TelegramUserbot\Backend\Shared\Infrastructure\Doctrine\DoctrineEventEntityRepository

doctrine:
  # Types
  dbal:
    types:
      name: olml89\TelegramUserbot\Backend\Shared\Infrastructure\Doctrine\Type\NameType
      percentage: olml89\TelegramUserbot\Backend\Shared\Infrastructure\Doctrine\Type\PercentageType
  # Mappings
  orm:
    entity_managers:
      default:
        mappings:
          EventEntity:
            is_bundle: false
            type: xml
            dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Event'
            prefix: olml89\TelegramUserbot\Backend\Shared\Domain\Entity\Event
            alias: EventEntity
