monolog:
  handlers:

    # Event logger (event channels exist because WebProfiler is enabled)
    events:
      type: stream
      path: /var/log/backend/events.log
      level: debug
      formatter: monolog.formatter.json
      channels:
        - event
