monolog:
  handlers:

    # Event logger (event channels exists because WebProfiler is enabled)
    events:
      type: stream
      path: /var/log/backend/events.log
      level: debug
      channels:
        - event
